config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :notes do
    resources :likes
  end  
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#user_dashboard"
  get 'user_notes', to: "notes#user_notes"
  post 'add_follower', to: 'users#add_follower'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: 'User' 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note 
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :title, presence:true
  validates :body, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence:true
  has_many :notes
  has_many :likes
  has_many :friendships
  has_many :followers, through: :friendships

  def not_followers_with?(follower_id)
    friendships.where(follower_id: follower_id).count < 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @follower = User.find(params[:id])
    @friendship = current_user.friendships.where(follower_id: params[:id]).first
    @friendship.destroy
    redirect_to user_path(@follower.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
    @like = Like.new(like_params)
  end

  def create
    @user = current_user.id
    @note = params[:note_id]
    note = Note.find(@note)
    likes = {user_id: @user,note_id: @note }
    @like = Like.new(likes)
    @like.save!
    UserMailer.like_email(note.user).deliver_now
    redirect_to user_path(note.user_id)
  end

  def destroy
    @user = current_user.id
    @note = params[:note_id]
    note = Note.find(@note)
    record = Like.where("user_id = ? and note_id = ?", @user, @note)
    recordss = record.ids.first
    Like.destroy(recordss)

    UserMailer.unlike_email(note.user).deliver_now
    redirect_to user_path(note.user_id)
  end

  def like_params
      params.require(:likes).permit(:user_id, :note_id)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render 'new'
    end
  end

  def edit
    @note = current_user.notes.find(params[:id])
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update(note_params)
      redirect_to notes_path(@note)
    else
      render 'edit'
    end
  end

  def destroy
     @note = current_user.notes.find(params[:id])
     @note.destroy
     redirect_to notes_path
  end

  def index
    @notes = Note.all
  end

  def user_notes
    @notes = current_user.notes.all
    @note = current_user.notes.new
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :like)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def user_dashboard

  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def my_followers
    @friendships = current_user.followers
  end

  def add_follower
    @follower = User.find(params[:follower])
    current_user.friendships.build(follower_id: @follower.id)
    if current_user.save
    redirect_to user_path(@follower.id), notice: "Friend was successfully added"
    else
    redirect_to user_path(@follower.id), flash[:error] = "There was an error with adding user as friend"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcFinalAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit your note</h1>
<% if @note.errors.any? %>

<h2>The following errors prevented the article from getting created</h2>

<ul>

<% @note.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>


<%= form_for @note, method: :PUT do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, 'Write Something' %><br/>
    <%= f.text_field :body %>
  </p>

  <%= f.submit 'Edit Note' %>
<% end %>

app/views/notes/index.html.erb
<h1>Listing all notes</h1>
<% @notes.each do |note| %>
<p><%= note.user_id %></p>
<p><%= note.title %></p>
<p><%= note.body %></p>
<p><%= link_to 'Delete', note_path(note), method: :delete, data:{confirm:"Are you sure?"} %></p>
<% end %>

app/views/notes/new.html.erb
<h1>Write a new note</h1>

<%= form_for @note do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, 'Write Something' %><br/>
    <%= f.text_field :body %>
  </p>

  <%= f.submit 'Create Note' %>
<% end %>

app/views/notes/show.html.erb
<h1>Current User Feed</h1>

<p><%= current_user.notes.title %></p>
<p><%= @note.body %></p>

app/views/notes/user_notes.html.erb
<h1>Current User's Notes</h1>

app/views/users/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Find Users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Find Users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/index.html.erb
<h1>My Non Followers</h1>

<% @users.each do |user| %>
  <% if current_user.not_followers_with?(user.id) %>
    <% if current_user.id != user.id %>
      <p>Profile of User_id: <%= user.id %></p>
    <p><%=link_to 'Go to profile', user_path(user.id) %></p>  
    <% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>Profile Page of User <%= @user.id %></h2>

<h3>My Notes</h3>

<% if current_user.id != @user.id %>
  <% if current_user.not_followers_with?(@user.id) %>
  <%= link_to "Follow", add_follower_path(user: current_user, follower: @user), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
    <%= link_to 'Unfollow', friendship_path(@user.id), method: :delete, class: "btn btn-xs btn-danger" %>
  <% end %>
<% end %>
<% @user.notes.each do |note| %>
    <p>Title: <%= note.title %></p>
    <p>Note: <%= note.body %></p>
    <% if Like.exists?(note_id: note.id) %>
      <% if Like.exists?(user_id: current_user.id) %>
        <% like_id = Like.where(["user_id = ? and note_id = ?", current_user.id, note.id]) %>
        <%= link_to 'Unlike', note_like_path(note.id, like_id), method: :delete %>
      <% end %>
    <% else %>
      <%= link_to 'Like', note_likes_path(note.id), method: :post %>
    <% end %>
<% end %>

app/views/users/user_dashboard.html.erb
<%= render 'navbar' %>

<h1>User Dashboard</h1>